import Head from 'next/head';
import Link from 'next/link';
import { useRef, useState } from 'react';
import { FiSearch } from 'react-icons/fi';

import styles from '../styles/home.module.scss'


export default function Home() {


  const [searchedUser,setSearchedUser] = useState("");


  return (
    <div className={styles.container}>
      <Head>
        <title>Github User Explorer | Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container_logo}>
        <img src="/images/github-logo.svg" alt="Github logo" />
        <span>
          Github Users Explorer
        </span>
      </div>

      <form>
        <h1>
          Explore usuários no Github
        </h1>
        <div className={styles.searchBar}>
          <input 
            type="search" 
            name="search_user" 
            id="search_user"
            placeholder = "Digite o nome do usuário" 
            autoComplete = "off"
            onChange = {(event) => setSearchedUser(event.target.value)}
            maxLength = "100"
          />
          <Link href = {`/usersInfo/${searchedUser}`}>
            <button>
              <FiSearch/> <span>Pesquisar</span>
            </button>
          </Link>
        </div>
      </form>


    </div>
  )
}
